[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'roxma/LanguageServer-php-neovim'
build = 'composer install && composer run-script parse-stubs'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo ='machakann/vim-highlightedyank'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'nightsense/snow'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'tobyS/pdv'

[[plugins]]
repo = 'Shougo/echodoc.vim'
