[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent> <C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'roxma/LanguageServer-php-neovim'
build = 'composer install && composer run-script parse-stubs'

[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo ='machakann/vim-highlightedyank'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/denite.nvim'
