[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent> <C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
'''

[[plugins]]
repo = 'roxma/LanguageServer-php-neovim'
build = 'composer install && composer run-script parse-stubs'

[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
hook_add = '''
inoremap <C-]> <Esc>:call PhpDocSingle()<CR>i
nnoremap <C-]> :call PhpDocSingle()<CR>
vnoremap <C-]> :call PhpDocSingle()<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo ='machakann/vim-highlightedyank'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  ctermbg=black
hi IndentGuidesEven ctermbg=darkgrey

'''
